# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 00:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device_id', models.TextField()),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
