# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consent_studyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='imageData',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
