# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20151229_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
