# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20151229_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
