# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20151229_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
