# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160330_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='place',
            field=models.TextField(null=True),
        ),
    ]
